### ISSUE TITLE
Error compiling vf_raisr

### ISSUE THREAD

**Issue by pguruva** [OpenVisualCloud/Video-Super-Resolution-Library#1]
Getting an error while compiling "libavfilter/vf_raisr".

*********************************************************************
CC      libavfilter/vf_raisr.o
In file included from /usr/local/include/raisr/RaisrHandler.h:9:0,
                 from libavfilter/vf_raisr.c:38:
/usr/local/include/raisr/RaisrDefaults.h:11:50: **error: initializer element is not constant**
static const unsigned int defaultPatchAreaSize = defaultPatchSize * defaultPatchSize;
*********************************************************************
The OS is Ubuntu 18.04 LTS, gcc version is 7.5.0

**Comment by xiaoxial** [comment]
The error occurs on lower GCC 7.5.0, but no the error on higher GCC such as GCC 9.4.0. And we will fix it for GCC 7.5.0.

**Comment by xiaoxial** [comment]
The issue has been fixed in v22.12.
