### ISSUE TITLE
[scripts/0x_buildscript] Link to IPP file returns 403 Forbidden

### ISSUE THREAD

**Issue by bbgdzxng1** [OpenVisualCloud/Video-Super-Resolution-Library#8]
1. Link for IPP file in scripts/01_pull_resources.sh is no longer valid.  It returns 403

```bash
$ curl --location --request GET 'https://registrationcenter-download.intel.com/akdlm/irc_nas/19007/l_ipp_oneapi_p_2021.6.2.16995_offline.sh' --head
HTTP/1.1 403 Forbidden
```
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>P1HKAT8M7JHH9E2X</RequestId><HostId>pktHIMr2BMSeo71zVDqw918+PVDhUC/ZVABGevEM6Sw5yBcAPDTyJ2KHLI5Pou27HJzD2aDF9Ew=</HostId></Error>
```

[Lines 66 & 67](https://github.com/OpenVisualCloud/Video-Super-Resolution-Library/blob/3e914f3f77cacc91c0c1d764b4234df5bd2dd8fd/scripts/01_pull_resources.sh#L66C1-L66C112) will need to be updated with updated URL...

```bash
# pull IPP
wget https://registrationcenter-download.intel.com/akdlm/IRC_NAS/7e07b203-af56-4b52-b69d-97680826a8df/l_ipp_oneapi_p_2021.12.1.16_offline.sh
if [ ! -f "l_ipp_oneapi_p_2021.12.1.16_offline.sh" ];then
    echo "Failed to download IPP package!"
    exit 1
fi
```
It may be more elegant to use a basename in the `[ test ]` commands
```bash
# pull IPP
ipp_offline_uri='https://registrationcenter-download.intel.com/akdlm/IRC_NAS/7e07b203-af56-4b52-b69d-97680826a8df/l_ipp_oneapi_p_2021.12.1.16_offline.sh'
wget "${ipp_offline_uri}"
if [ ! -f "${ipp_offline_uri##*/}" ];then
    echo "Failed to download IPP package!"
    exit 1
fi
```

2. Same goes for [lines 17-19](https://github.com/OpenVisualCloud/Video-Super-Resolution-Library/blob/3e914f3f77cacc91c0c1d764b4234df5bd2dd8fd/scripts/02_install_prerequisites.sh#L17) in scripts/02_install_prerequisites.sh

```
# install IPP
chmod +x ./l_ipp_oneapi_p_2021.12.1.16_offline.sh
sudo ./l_ipp_oneapi_p_2021.12.1.16_offline.sh -a -s --eula accept
echo "source /opt/intel/oneapi/ipp/latest/env/vars.sh" | tee -a ~/.bash_profile
```
It may also be preferable to save locally as a versionless file name, ./ipp_oneapi_offline_latest.sh, so that 02_install_prerequisites does not need to be continuously updated.

Thanks

**Comment by Fiooodooor** [comment]
I @bbgdzxng1 appreciate your effort in project development, thanks for code snippets! Hope all of the issues and bugs, including ones pointed by you, will be fully addressed in upcoming major version release of Intel® Library for Video Super Resolution. The most significant is one regarding GPU build using CentOS build, there will be migration to CentOS 9, and update to Dockerfile structures to meet the highest containers standards.

For now, as internal release takes some time, I encourage you to check the optimized all-in-one environment and weekly updated project: 
[Intel® Tiber™ Broadcast Suite package docker build script](https://github.com/OpenVisualCloud/Intel-Tiber-Broadcast-Suite/blob/main/build.sh)

It includes GPU and CPU based RAISR ffmpeg plugin as well as set of other optimizations and functionalities.

RAISR part: [Intel® Library for Video Super Resolution (RAISR) for Intel® Tiber™ Broadcast Suite](https://github.com/OpenVisualCloud/Intel-Tiber-Broadcast-Suite?tab=readme-ov-file#23-intel-library-for-video-super-resolution-raisr-for-intel-tiber-broadcast-suite)

![image](https://github.com/user-attachments/assets/032c4107-0fb4-4c2b-ac11-62bff8847ff2)

**Comment by Mionsz** [comment]
https://github.com/OpenVisualCloud/Video-Super-Resolution-Library/pull/11

**Comment by bbgdzxng1** [comment]
Closed, thanks to @Mionsz.
